[package]
publish = true
name = "ydb-grpc"
version = "0.0.7"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Crate contains generated low-level grpc code from YDB API protobuf, used as base for ydb crate"
repository = "https://github.com/ydb-platform/ydb-rs-sdk/tree/master/ydb-grpc"

[dependencies]
prost = "0.10"
prost-types = "0.10"
pbjson = "0.3"
pbjson-types = "0.3"
serde={version="1.0", features=["derive"]}
tonic = {version = "0.8", features=["tls", "tls-roots", "tls-webpki-roots"]}

[build-dependencies]
ydb-grpc-helpers = { version = "0.0.7", path="../ydb-grpc-helpers"}
prost-build = "0.10"
pbjson-build="0.3"
tonic-build = "0.7"
walkdir = "2"

[features]
regenerate-sources = []
